# Generated by Django 5.0.6 on 2024-09-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="quotes.author",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(related_name="quotes", to="quotes.tag"),
        ),
    ]
