# Generated by Django 5.0.6 on 2024-11-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_quote_author_alter_quote_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
